[package]
name = "tinytoken"
version = "0.1.0"
edition = "2021"
description = "Library for tokenizing text into words, numbers, symbols, and more, with customizable parsing options."
license = "MIT"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
